## Control Vars
TARGET_NO_BOOTLOADER := true
TARGET_NO_RECOVERY := true

TARGET_USERIMAGES_USE_EXT4 := true


#TARGET_COPY_OUT_VENDOR := vendor
#TARGET_COPY_OUT_PRODUCT := product
# TARGET_COPY_OUT_SYSTEM_EXT := system_ext

BOARD_AVB_ENABLE := true
BOARD_AVB_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)


## XC-TODO
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
ALLOW_MISSING_DEPENDENCIES := true
#TARGET_SUPPORTS_OMX_SERVICE := false
#PRODUCT_USES_DEFAULT_ART_CONFIG := false
## If we have such files
PRODUCT_ARTIFACT_PATH_REQUIREMENT_ALLOWED_LIST +=


